[2022-01-22 17:34:48,716] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_sorocaba 2022-01-22T20:34:36.418839+00:00 [queued]>
[2022-01-22 17:34:48,724] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: twitter_dag.twitter_sorocaba 2022-01-22T20:34:36.418839+00:00 [queued]>
[2022-01-22 17:34:48,724] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2022-01-22 17:34:48,724] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2022-01-22 17:34:48,724] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2022-01-22 17:34:48,738] {taskinstance.py:901} INFO - Executing <Task(TwitterOperator): twitter_sorocaba> on 2022-01-22T20:34:36.418839+00:00
[2022-01-22 17:34:48,741] {standard_task_runner.py:54} INFO - Started process 6594 to run task
[2022-01-22 17:34:48,808] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'twitter_dag', 'twitter_sorocaba', '2022-01-22T20:34:36.418839+00:00', '--job_id', '15', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/twitter_dag.py', '--cfg_path', '/tmp/tmpfpaiea6_']
[2022-01-22 17:34:48,809] {standard_task_runner.py:78} INFO - Job 15: Subtask twitter_sorocaba
[2022-01-22 17:34:48,830] {logging_mixin.py:112} INFO - Running <TaskInstance: twitter_dag.twitter_sorocaba 2022-01-22T20:34:36.418839+00:00 [running]> on host nicholas-VirtualBox-ubuntu1804
[2022-01-22 17:34:48,841] {taskinstance.py:1150} ERROR - unexpected 'end of template'
Traceback (most recent call last):
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 965, in _run_raw_task
    self.render_templates(context=context)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1424, in render_templates
    self.task.render_template_fields(context)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 719, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 726, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 764, in render_template
    return tuple(self.render_template(element, context, jinja_env) for element in content)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 764, in <genexpr>
    return tuple(self.render_template(element, context, jinja_env) for element in content)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 755, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/nicholas/datapipeline/.env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected 'end of template'
[2022-01-22 17:34:48,846] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=twitter_dag, task_id=twitter_sorocaba, execution_date=20220122T203436, start_date=20220122T203448, end_date=20220122T203448
[2022-01-22 17:34:53,727] {local_task_job.py:102} INFO - Task exited with return code 1
